version: '3.1'

services:
  web:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - static:/app/static
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8083:80
    volumes:
      - static:/app/static
    depends_on:
      - web

  db:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 8082:80
    depends_on:
      - db

volumes:
  pgdata:
  static:


networks:
  default:
    driver: bridge