version: '3.1'

services:
  web:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    expose:
      - 8000
    volumes:
      - static:/app/static
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - netdjango

  nginx:
    build: ./nginx
    ports:
      - 8083:80
    volumes:
      - static:/app/static
    depends_on:
      - web
    links:
      - web:web
    networks:
      - netdjango

  db:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - netdjango

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - netdjango

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 8082:80
    depends_on:
      - db
    networks:
      - netdjango

volumes:
  pgdata:
  static:

networks:
  netdjango:
    driver: bridge