version: '3.1'

services:

  db:
    image: postgres:10-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - netapp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - netapp
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 8082:80
    networks:
      - netapp
    depends_on:
      - db

volumes:
  pgdata:
  
networks:
  netapp:
    driver: bridge